version: "3"
services:
    docker-mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=tema2
            - MYSQL_PASSWORD=1q2w3e
        ports:
          - "33061:3306"
        volumes:
              - ./src/main/resources/dbscripts:/docker-entrypoint-initdb.db         
    spring-boot-service:
        image: test
        depends_on:
           - docker-mysql
        ports:
           - "8005:8080"
        environment:
           - DATABASE_HOST=docker-mysql
           - DATABASE_USER=root
           - DATABASE_PASSWORD=1q2w3e
           - DATABASE_NAME=tema2  
           - DATABASE_PORT=3306
